import { UserProvider } from "../contexts/UserContext";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import HeaderNav from "../components/Menu/HeaderNav";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Media Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <UserProvider>
          {/* Sử dụng flexbox để Footer luôn nằm dưới đáy 
            nếu nội dung trang quá ngắn 
          */}
          <div className="flex flex-col min-h-screen">
            


            {/* Main content - flex-grow sẽ đẩy footer xuống */}
            <main className="flex-grow">
              {children}
            </main>

            {/* Footer */}
            
          </div>
        </UserProvider>
      </body>
    </html>
  );
}