import { UserProvider } from "../contexts/UserContext";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";



const inter = Inter({
  subsets: ["latin", "vietnamese"], // Support Vietnamese
  variable: "--font-inter",         // CSS variable for Tailwind
  display: "swap",
});

export const metadata: Metadata = {
  title: "Media Hub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.variable}>
      <body
       className="antialiased font-sans bg-[#0a0a0a] text-white"
      >
        <UserProvider>
          <div className="flex flex-col min-h-screen">
            <main className="flex-grow">
              {children}
            </main>
          </div>
        </UserProvider>
      </body>
    </html>
  );
}